language: objective-c
osx_image: xcode9.3
xcode_workspace: TravisTest.xcworkspace
xcode_scheme: TravisTest
podfile: Podfile
before_install:
- pod install
before_script:
- ./scripts/decrypt-cert.sh
- ./scripts/add-key.sh
- gem install CFPropertyList
- gem install sqlite3
- gem install digest
script:
- ./scripts/build.sh
after_script:
- ./scripts/remove-key.sh
deploy:
      provider: releases
      prerelease: true
      skip_cleanup: true
      file_glob: true
      github-token: $GIT_TOKEN
      file: "*.ipa"
      keep-history: true
      on:
        branch: master